development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rapidnomadic_development
  pool: 5
  port: 3306
  username: root
  password:
  socket: /tmp/mysql.sock



test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rapidnomadic_test
  pool: 5
  port: 3306
  username: root
  password:
  socket: /tmp/mysql.sock


